### ISSUE TITLE
Line of code (for me) prevents finding of images

### ISSUE THREAD

**Issue by BigWub67** [JamesSG2/Handwriting-Conversion-Application#18]
This line of code:
![problem1](https://user-images.githubusercontent.com/80499657/114105455-9f8db700-9881-11eb-94c4-bf5e33ba4402.PNG)
Makes this happen:
![problem2](https://user-images.githubusercontent.com/80499657/114105598-e4195280-9881-11eb-8eba-88a0479bb562.PNG)
Basically, it prevents the program (for me) from finding the files correctly for me anywhere it shows up (in this instance, it happened in the main method in main.py in the feature-output branch).

When I comment it out:
![problem3](https://user-images.githubusercontent.com/80499657/114105662-01e6b780-9882-11eb-86b0-f38d78806fbb.PNG)
It actually works:
![problem4](https://user-images.githubusercontent.com/80499657/114105690-0f03a680-9882-11eb-86f9-da9efbf24674.PNG)

This is probably occurring because I'm running the code with VS Code which just runs the code.

It shouldn't matter when we get the GUI going though since it will pass through the whole path, but I felt like I should bring this up.

**Comment by rover-t** [comment]
Okay, that probably happens because of how the initial directory is set. The way it is for me the directory starts out in the \src\ folder, so I move it up one directory to the \Handwriting-Coversion-Application\ folder, so it can then look in the \output\ and \data\ folders. If you are using VS Code, then maybe it starts in the project folder, which is probably \Handwriting-Coversion-Application\.
